version: '3.8'

services:
  postgres_db:
    image: postgres
    container_name: postgres-empresa
    environment:
      POSTGRES_DB: empresa_produto
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
  empresa-produto-api:
    image: diegoafmelo/empresa-produto-api:1.0.0
    container_name: empresa-produto-api
    environment:
      - SERVER_PORT=8080
      - MYAPP_JDBC_URL=jdbc:postgresql://postgres_db:5432/empresa_produto
      - MYAPP_JDBC_USER=postgres
      - MYAPP_JDBC_PASS=postgres
    ports:
      - "8080:8080"
    links:
      - postgres_db:postgres_db
volumes:
  postgres: